// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build.
import handler from "./.open-next/worker.js";

type WorkerEnv = {
  CRON_SECRET?: string;
};

type ScheduledController = {
  scheduledTime: number;
};

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

const worker = {
  fetch: handler.fetch,

  async scheduled(
    event: ScheduledController,
    env: WorkerEnv,
    context: WorkerContext,
  ) {
    if (!env.CRON_SECRET) {
      throw new Error("CRON_SECRET is not configured.");
    }

    const response = await handler.fetch(
      new Request("https://internal.bhada/api/cron/rent-bills", {
        method: "POST",
        headers: {
          authorization: `Bearer ${env.CRON_SECRET}`,
          "x-scheduled-time": String(event.scheduledTime),
        },
      }),
      env,
      context,
    );

    if (!response.ok) {
      throw new Error(`Monthly rent billing failed with status ${response.status}.`);
    }
  },
};

export default worker;
